name: app
type: 'php:8.0'

# The build flavor determines how Platform.sh builds your app.
build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      allow: true

relationships:
    database: "db:mysql"
    redis: "redis:redis"
