name: app
type: 'php:8.1'
disk: 2048

dependencies:
    php:
        composer/composer: "^2"

build:
  flavor: composer

web:
    locations:
        "/":
            root: "web"
            index: [index.php]

relationships:
    database: "db:mysql"
    redis: "redis:redis"
