name: app
type: 'php:8.1'
disk: 2048

hooks:
    build: |
        set -e
        composer install --prefer-dist --no-progress --no-interaction

web:
    locations:
        "/":
            root: "web"
            passthru: "/index.php"
            index:
                - index.php
                - index.html

relationships:
    database: "db:mysqldump"
    redis: "redis:redis"
